;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ac-pcmp/self-insert-command-with-ac-start
	hungry-delete-backward
	hungry-delete-forward
	))

(setq mc/cmds-to-run-once
      '(
	org-cycle
	text-scale-adjust
	))
